version: '3.9'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: posts-db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  rest-service:
    depends_on:
      - db
    image: rest-service
    restart: always
    environment:
      MYSQL_URL: jdbc:mysql://db:3307/posts-db
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "8080:8080"
volumes:
  db_data: {}
