version: '3.9'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: posts-db
      MYSQL_USER: java_to_dev
      MYSQL_PASSWORD: nE5kMc7JCGNqwDQM
      MYSQL_ROOT_PASSWORD: nE5kMc7JCGNqwDQN
    ports:
      - "3307:3307"
  rest-service:
    image: rest-service
    restart: always
    depends_on:
      - db
    environment:
      MYSQL_URL: jdbc:mysql://db:3307/posts-db
      MYSQL_USER: java_to_dev
      MYSQL_PASSWORD: nE5kMc7JCGNqwDQM
    ports:
      - "8080:8080"
volumes:
  db_data: {}