version: '3.9'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: posts_db
      MYSQL_USER: gal
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
  rest-service:
    image: rest-service
    restart: always
    depends_on:
      - db
    environment:
      MYSQL_URL: jdbc:mysql://db:3307/posts_db
      MYSQL_USER: gal
      MYSQL_PASSWORD: 1234
    ports:
      - "8080:8080"
volumes:
  db_data: {}